# Generated by Django 5.1.6 on 2025-02-20 00:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactrequest',
            name='contact_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact.contactinfo'),
        ),
    ]
