# Generated by Django 5.1.6 on 2025-04-14 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_alter_contactrequest_contact_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactrequest',
            name='reason_for_the_inquiry',
            field=models.CharField(choices=[('For a question', 'Question'), ('For a collaboration', 'Collaboration'), ('For a sponsorship', 'Sponsorship'), ('For another reason', 'Other')], default='For another reason', max_length=20),
        ),
    ]
